export const courses = [
 {
  id: 1,
  title: "Office 365",
  desc: "Master the Office productivity suite for business needs.",
  category: "Digital Tools",
  level: "Beginner",
  duration: "56 hours",
  modules: 10,
    image: "Office-365-Logotipo-2020.jpg",
  objectives: [
    "Master Word, Excel, PowerPoint, and Outlook",
    "Collaborate effectively using Teams and SharePoint",
    "Manage email and calendar efficiently",
    "Create professional presentations and reports",
  ],
  curriculum: [{
        name: "Word Processing Fundamentals",
        subModules: [
          "Introduction to Word",
          "Document Formatting",
          "Working with Tables",
          "Mail Merge",
          "Proofreading Tools",
        ],
      },
      {
        name: "Excel Basics and Formulas",
        subModules: [
          "Spreadsheet Navigation",
          "Basic Arithmetic Formulas",
          "Cell Referencing",
          "Data Entry Best Practices",
          "Conditional Formatting",
          "Basic Charting",
          "Data Validation",
        ],
      },
      {
        name: "PowerPoint Design Principles",
        subModules: ["Slide Layouts", "Visual Hierarchy", "Animation Basics", "Presentation Delivery Tips"],
      },
      {
        name: "Outlook Email Management",
        subModules: ["Email Basics", "Calendar Management", "Contact Management", "Task Organization"],
      },
      {
        name: "Teams Collaboration",
        subModules: ["Chat and Channels", "Meetings and Calls", "File Sharing", "App Integration"],
      },
      {
        name: "SharePoint Document Management",
        subModules: ["Document Libraries", "Version Control", "Permissions", "Site Navigation"],
      },
      {
        name: "Advanced Features Integration",
        subModules: ["Power Automate Integration", "Forms and Surveys", "OneNote Integration", "Advanced Security"],
      },
      {
        name: "Project-based Assessment",
        subModules: ["Project Planning", "Execution and Monitoring", "Reporting", "Final Review"],
      },
  
  ],
  prerequisites: "Basic computer knowledge",
  certification: "Microsoft Office Specialist",
   quizzes: [
      {
        id: 101,
        title: "Office 365 Fundamentals Quiz",
        description: "Test your basic knowledge of Office 365 applications.",
        questions: [
          {
            id: 1,
            text: "Which Office 365 application is primarily used for word processing?",
            type: "multiple-choice",
            options: ["Excel", "PowerPoint", "Word", "Outlook"],
            correctAnswer: "Word",
          },
          {
            id: 2,
            text: "True or False: Microsoft Teams is used for collaboration and communication.",
            type: "true-false",
            options: ["True", "False"],
            correctAnswer: "True",
          },
          {
            id: 3,
            text: "What is the main purpose of Microsoft Excel?",
            type: "text",
            correctAnswer: "Spreadsheet creation and data analysis",
          },
          {
            id: 4,
            text: "Which application is best for creating professional presentations?",
            type: "multiple-choice",
            options: ["Word", "Excel", "PowerPoint", "Outlook"],
            correctAnswer: "PowerPoint",
          },
        ],
      },
      {
        id: 102,
        title: "Advanced Office 365 Features Quiz",
        description: "Assess your understanding of advanced features and integrations.",
        questions: [
          {
            id: 1,
            text: "Which feature in Excel allows you to automate repetitive tasks?",
            type: "multiple-choice",
            options: ["Pivot Tables", "Macros", "Conditional Formatting", "Data Validation"],
            correctAnswer: "Macros",
          },
          {
            id: 2,
            text: "True or False: SharePoint is primarily used for email management.",
            type: "true-false",
            options: ["True", "False"],
            correctAnswer: "False",
          },
          {
            id: 3,
            text: "What is the primary function of Power Automate within Office 365?",
            type: "text",
            correctAnswer: "Automating workflows and tasks",
          },
        ],
      },
    ],
  },
  

{
  id: 2,
  title: "Computer Training for Cluster",
  desc: "Basic digital literacy and system usage training.",
  category: "Technical",
  level: "Beginner",
  duration: "26 hours",
  modules: 9,
  image:"computer-cluster-handling-big-data-processing-neural-network-training-310866977.webp",
  objectives: [
    "Understand computer fundamentals",
    "Navigate operating systems effectively",
    "Use basic software applications",
    "Practice digital safety and security",
  ],
  curriculum:[
      { name: "Computer Hardware Basics", subModules: ["Components", "Peripherals", "Maintenance"] },
      { name: "Operating System Navigation", subModules: ["Windows Basics", "File Explorer", "Settings"] },
      { name: "File Management", subModules: ["Folders", "Copy/Move", "Compression"] },
      { name: "Internet and Email Basics", subModules: ["Browsing", "Email Sending", "Attachments"] },
      { name: "Basic Troubleshooting", subModules: ["Common Issues", "Restarting", "Updates"] },
      { name: "Digital Security Best Practices", subModules: ["Passwords", "Phishing", "Antivirus"] },
    ],
    prerequisites: "None",
    certification: "Digital Literacy Certificate",
quizzes: [
      {
        id: 201,
        title: "Computer Basics Quiz",
        description: "A quick quiz on fundamental computer concepts.",
        questions: [
          {
            id: 1,
            text: "Which of these is an input device?",
            type: "multiple-choice",
            options: ["Monitor", "Printer", "Keyboard", "Speaker"],
            correctAnswer: "Keyboard",
          },
          {
            id: 2,
            text: "True or False: RAM is a type of long-term storage.",
            type: "true-false",
            options: ["True", "False"],
            correctAnswer: "False",
          },
        ],
      },
    ],
  },
  
{
  id: 3,
  title: "Microsoft Excel - Basic",
  desc: "Learn the fundamentals of Microsoft Excel.",
  category: "Digital Tools",
  level: "Beginner",
  duration: "36 hours",
  modules: 10,
  image:"Microsoft-Excel-Logo.jpg",
  objectives: [
    "Create and format spreadsheets",
    "Use basic formulas and functions",
    "Create charts and graphs",
    "Manage data effectively",
  ],
  curriculum:   [
      { name: "Excel Interface and Navigation", subModules: ["Ribbon", "Worksheets", "Cells"] },
      { name: "Data Entry and Formatting", subModules: ["Text", "Numbers", "Dates", "Cell Styles"] },
      { name: "Basic Formulas and Functions", subModules: ["SUM", "AVERAGE", "COUNT", "Basic Operators"] },
      { name: "Working with Charts", subModules: ["Column Charts", "Line Charts", "Pie Charts"] },
      { name: "Data Sorting and Filtering", subModules: ["Basic Sort", "Custom Sort", "AutoFilter"] },
      { name: "Print Setup and Page Layout", subModules: ["Print Area", "Page Breaks", "Headers/Footers"] },
      { name: "Basic Data Analysis", subModules: ["Subtotals", "Conditional Sums"] },
      { name: "Practical Applications", subModules: ["Budgeting", "Simple Tracking"] },
    ],
    prerequisites: "Basic computer skills",
    certification: "Excel Basic Proficiency",
quizzes: [
      {
        id: 301,
        title: "Excel Basic Functions Quiz",
        description: "A quiz on fundamental Excel functions and features.",
        questions: [
          {
            id: 1,
            text: "Which function is used to add a range of numbers in Excel?",
            type: "multiple-choice",
            options: ["AVERAGE", "COUNT", "SUM", "MAX"],
            correctAnswer: "SUM",
          },
          {
            id: 2,
            text: "True or False: You can create charts in Excel to visualize data.",
            type: "true-false",
            options: ["True", "False"],
            correctAnswer: "True",
          },
        ],
      },
    ],
  },
{
  id: 4,
  title: "Advanced Microsoft Excel",
  desc: "Advanced tools and features in Excel for data professionals.",
  category: "Digital Tools",
  level: "Advanced",
  duration: "48 hours",
  modules: 12,
  image:"advanced-excel-banner.png",
  objectives: [
    "Master advanced formulas and functions",
    "Create dynamic dashboards",
    "Use pivot tables and data analysis tools",
    "Automate tasks with macros",
  ],
  curriculum:  [
      { name: "Advanced Formulas (VLOOKUP, INDEX, MATCH)", subModules: ["VLOOKUP", "HLOOKUP", "INDEX/MATCH"] },
      { name: "Pivot Tables and Pivot Charts", subModules: ["Creating Pivots", "Slicers", "Calculated Fields"] },
      { name: "Data Analysis Tools", subModules: ["Goal Seek", "Solver", "Data Tables"] },
      { name: "Dashboard Creation", subModules: ["Design Principles", "Interactive Elements"] },
      { name: "VBA and Macro Programming", subModules: ["Recording Macros", "Editing VBA", "User Forms"] },
      { name: "Advanced Data Modeling", subModules: ["Power Query", "Data Model", "Relationships"] },
    ],
    prerequisites: "Excel Basic course completion",
    certification: "Excel Advanced Professional",
  quizzes: [
      {
        id: 401,
        title: "Advanced Excel Formulas Quiz",
        description: "Test your knowledge of complex Excel formulas.",
        questions: [
          {
            id: 1,
            text: "Which function is best for looking up values in a table based on multiple criteria?",
            type: "multiple-choice",
            options: ["VLOOKUP", "INDEX/MATCH", "SUMIF", "COUNTIF"],
            correctAnswer: "INDEX/MATCH",
          },
          {
            id: 2,
            text: "True or False: Macros can automate repetitive tasks in Excel.",
            type: "true-false",
            options: ["True", "False"],
            correctAnswer: "True",
          },
        ],
      },
    ],
  },
  {
    id: 5,
    title: "React JS",
    desc: "Build modern web applications using React framework.",
    category: "Technical",
    level: "Intermediate",
    duration: "60 hours",
    modules: 15,
    image: "react-1-logo-png-transparent.png",
    objectives: [
      "Build interactive web applications",
      "Master React components and hooks",
      "Implement state management",
      "Deploy production-ready applications",
    ],
    curriculum: [
      { name: "JavaScript ES6+ Fundamentals", subModules: ["Arrow Functions", "Destructuring", "Promises"] },
      {
        name: "React Components and JSX",
        subModules: [
          "Understanding Components",
          "JSX Syntax",
          "Functional Components",
          "Class Components",
          "Component Lifecycle",
        ],
      },
      { name: "State and Props Management", subModules: ["useState Hook", "Props Drilling", "Context API Intro"] },
      { name: "React Hooks", subModules: ["useEffect", "useContext", "useReducer", "Custom Hooks"] },
      { name: "Routing and Navigation", subModules: ["React Router DOM", "Nested Routes", "Programmatic Navigation"] },
      { name: "API Integration", subModules: ["Fetching Data (Fetch/Axios)", "Error Handling", "Loading States"] },
      { name: "Testing and Debugging", subModules: ["Jest/React Testing Library", "Browser Dev Tools"] },
      { name: "Deployment and Best Practices", subModules: ["Build Process", "Performance Optimization", "Security"] },
    ],
    prerequisites: "HTML, CSS, JavaScript knowledge",
    certification: "React Developer Certificate",
quizzes: [
      {
        id: 501,
        title: "React JS Basics Quiz",
        description: "A quiz on fundamental React concepts.",
        questions: [
          {
            id: 1,
            text: "What is JSX in React?",
            type: "multiple-choice",
            options: ["A JavaScript library", "A syntax extension for JavaScript", "A CSS preprocessor", "A database"],
            correctAnswer: "A syntax extension for JavaScript",
          },
          {
            id: 2,
            text: "True or False: React is a full-stack framework.",
            type: "true-false",
            options: ["True", "False"],
            correctAnswer: "False",
          },
          {
            id: 3,
            text: "Which hook is used for managing state in functional components?",
            type: "multiple-choice",
            options: ["useEffect", "useContext", "useState", "useReducer"],
            correctAnswer: "useState",
          },
          {
            id: 4,
            text: "True or False: Props are used to pass data from a parent component to a child component.",
            type: "true-false",
            options: ["True", "False"],
            correctAnswer: "True",
          },
        ],
      },
    ],
  },

 

{
  id: 6,
  title: "SAP PM (Plant Maintenance)",
  desc: "Understand SAP's Plant Maintenance module.",
  category: "Technical",
  level: "Intermediate",
  duration: "80 hours",
  modules: 20,
  image:"SAP-PM-logo.webp",
  objectives: [
    "Master SAP PM module functionality",
    "Manage maintenance orders and work orders",
    "Handle equipment and asset management",
    "Generate maintenance reports",
  ],
  curriculum: [
      { name: "SAP PM Introduction and Navigation", subModules: ["Overview", "System Access", "User Interface"] },
      { name: "Equipment Master Data", subModules: ["Creating Equipment", "Functional Locations", "BOMs"] },
      { name: "Maintenance Planning", subModules: ["Task Lists", "Maintenance Plans", "Scheduling"] },
      { name: "Work Order Management", subModules: ["Creating Orders", "Processing Orders", "Confirmations"] },
      { name: "Preventive Maintenance", subModules: ["Strategy Plans", "Time-Based Plans", "Counter-Based Plans"] },
      { name: "Material Management Integration", subModules: ["Reservations", "Goods Issue", "Stock Overview"] },
      { name: "Cost Management", subModules: ["Cost Planning", "Settlement", "Reporting"] },
      { name: "Reporting and Analytics", subModules: ["Standard Reports", "Custom Reports", "KPIs"] },
      { name: "Mobile Plant Maintenance", subModules: ["Mobile Solutions", "Offline Capabilities"] },
      { name: "Project Implementation", subModules: ["Blueprint", "Configuration", "Go-Live"] },
    ],
    prerequisites: "Basic SAP knowledge recommended",
    certification: "SAP PM Certified Professional",
quizzes: [
      {
        id: 601,
        title: "SAP PM Fundamentals Quiz",
        description: "Test your understanding of basic SAP PM concepts.",
        questions: [
          {
            id: 1,
            text: "What does PM stand for in SAP PM?",
            type: "multiple-choice",
            options: ["Project Management", "Plant Maintenance", "Process Manufacturing", "Production Monitoring"],
            correctAnswer: "Plant Maintenance",
          },
          {
            id: 2,
            text: "True or False: Equipment Master Data is crucial for effective maintenance planning.",
            type: "true-false",
            options: ["True", "False"],
            correctAnswer: "True",
          },
          {
            id: 3,
            text: "What is the purpose of a Maintenance Plan in SAP PM?",
            type: "text",
            correctAnswer: "To schedule and manage recurring maintenance activities",
          },
        ],
      },
    ],
  },
{
  id: 7,
  title: "Data Analytics & Data Science",
  desc: "Explore data insights and develop predictive models.",
  category: "Technical",
  level: "Advanced",
  duration: "100 hours",
  modules: 25,
  image:"data-science-analytic-logo-design-isolated-vector-illustration_595532-249.avif",
  objectives: [
    "Analyze complex datasets",
    "Build predictive models",
    "Use statistical analysis tools",
    "Present data-driven insights",
  ],
  curriculum: [
      { name: "Statistics and Probability", subModules: ["Descriptive Stats", "Inferential Stats", "Distributions"] },
      { name: "Python for Data Science", subModules: ["NumPy", "Pandas", "Matplotlib"] },
      { name: "Data Cleaning and Preparation", subModules: ["Missing Values", "Outliers", "Normalization"] },
      { name: "Exploratory Data Analysis", subModules: ["Visualizations", "Correlations", "Hypothesis Testing"] },
      { name: "Machine Learning Basics", subModules: ["Supervised vs Unsupervised", "Model Evaluation"] },
      { name: "Supervised Learning", subModules: ["Regression", "Classification", "Decision Trees"] },
      { name: "Unsupervised Learning", subModules: ["Clustering", "Dimensionality Reduction"] },
      { name: "Deep Learning Introduction", subModules: ["Neural Networks", "TensorFlow/PyTorch"] },
      { name: "Big Data Technologies", subModules: ["Hadoop", "Spark", "NoSQL Databases"] },
      { name: "Data Visualization", subModules: ["Seaborn", "Plotly", "Dashboards"] },
      { name: "A/B Testing and Experimentation", subModules: ["Design", "Analysis", "Interpretation"] },
      { name: "Model Deployment", subModules: ["Flask/Django", "Docker", "Cloud Platforms"] },
      {
        name: "Capstone Project",
        subModules: ["Problem Definition", "Data Collection", "Model Building", "Presentation"],},],
      
  prerequisites: "Statistics background helpful",
  certification: "Data Science Professional",
quizzes: [
      {
        id: 701,
        title: "Data Science Concepts Quiz",
        description: "A quiz on core data science concepts.",
        questions: [
          {
            id: 1,
            text: "Which of these is a common library for data manipulation in Python?",
            type: "multiple-choice",
            options: ["Matplotlib", "Scikit-learn", "Pandas", "TensorFlow"],
            correctAnswer: "Pandas",
          },
          {
            id: 2,
            text: "True or False: Supervised learning requires labeled data.",
            type: "true-false",
            options: ["True", "False"],
            correctAnswer: "True",
          },
        ],
      },
    ],
  },
{
  id: 8,
  title: "Visualization - Tableau",
  desc: "Create compelling dashboards and data stories with Tableau.",
  category: "Digital Tools",
  level: "Intermediate",
  duration: "40 hours",
  modules: 10,
  image:"TABLEAU_SOFTWARE_LOGOjpg_Logo.jpg",
  objectives: [
    "Create interactive dashboards",
    "Design compelling visualizations",
    "Connect to various data sources",
    "Share insights effectively",
  ],
  curriculum:[
      { name: "Tableau Desktop Introduction", subModules: ["Interface", "Data Pane", "Worksheet"] },
      { name: "Data Connections and Preparation", subModules: ["Connect to Data", "Joins", "Unions"] },
      { name: "Basic Chart Types", subModules: ["Bar Charts", "Line Charts", "Scatter Plots"] },
      { name: "Advanced Visualizations", subModules: ["Maps", "Treemaps", "Gantt Charts"] },
      { name: "Dashboard Design Principles", subModules: ["Layout", "Interactivity", "Best Practices"] },
      { name: "Interactive Features", subModules: ["Filters", "Parameters", "Actions"] },
      { name: "Calculated Fields and Parameters", subModules: ["Basic Calculations", "LOD Expressions"] },
      { name: "Data Blending and Joins", subModules: ["Blending Data", "Cross-Database Joins"] },
      { name: "Publishing and Sharing", subModules: ["Tableau Server/Cloud", "Exporting"] },
      { name: "Advanced Analytics Features", subModules: ["Forecasting", "Clustering", "Trend Lines"] },
    ],
    prerequisites: "Basic data analysis knowledge",
    certification: "Tableau Desktop Specialist",
  quizzes: [
      {
        id: 801,
        title: "Tableau Basics Quiz",
        description: "Test your understanding of fundamental Tableau concepts.",
        questions: [
          {
            id: 1,
            text: "What is the primary purpose of Tableau?",
            type: "multiple-choice",
            options: ["Database Management", "Word Processing", "Data Visualization", "Web Development"],
            correctAnswer: "Data Visualization",
          },
          {
            id: 2,
            text: "True or False: You can connect Tableau to various data sources like Excel, SQL databases, etc.",
            type: "true-false",
            options: ["True", "False"],
            correctAnswer: "True",
          },
        ],
      },
    ],
  },
{
  id: 9,
  title: "Power Automate",
  desc: "Automate repetitive tasks and workflows with Power Automate.",
  category: "Digital Tools",
  level: "Intermediate",
  duration: "32 hours",
  modules: 8,
  image:"OIP.jpg",
  objectives: [
    "Design automated workflows",
    "Integrate multiple applications",
    "Reduce manual tasks",
    "Monitor and optimize flows",
  ],
  curriculum: 
    [
      { name: "Power Platform Overview", subModules: ["Power Apps", "Power BI", "Power Automate"] },
      { name: "Flow Creation Basics", subModules: ["Triggers", "Actions", "Connectors"] },
      { name: "Triggers and Actions", subModules: ["Automated Flows", "Instant Flows", "Scheduled Flows"] },
      { name: "Conditional Logic", subModules: ["If/Else", "Switch", "Loops"] },
      { name: "Data Operations", subModules: ["Compose", "Parse JSON", "Select"] },
      { name: "Integration with Office 365", subModules: ["SharePoint", "Outlook", "Excel Online"] },
      { name: "Error Handling and Testing", subModules: ["Run History", "Error Notifications"] },
      { name: "Advanced Scenarios and Best Practices", subModules: ["Approvals", "RPA", "Governance"] },
    ],
    prerequisites: "Office 365 familiarity",
    certification: "Power Platform Fundamentals",
  quizzes: [
      {
        id: 901,
        title: "Power Automate Basics Quiz",
        description: "Test your knowledge of Power Automate fundamentals.",
        questions: [
          {
            id: 1,
            text: "What is the main purpose of Power Automate?",
            type: "multiple-choice",
            options: ["Data Analysis", "Workflow Automation", "Presentation Design", "Database Management"],
            correctAnswer: "Workflow Automation",
          },
          {
            id: 2,
            text: "True or False: Power Automate can integrate with various Microsoft and third-party services.",
            type: "true-false",
            options: ["True", "False"],
            correctAnswer: "True",
          },
        ],
      },
    ],
  },
  {


  id: 10,
  title: "Generative AI & Creativity",
  desc: "Explore how Generative AI is transforming work and innovation.",
  category: "Emerging Tech",
  level: "Beginner",
  duration: "24 hours",
  modules: 6,
  image:"ai-logo-high-technology-logo-generative-ai_888418-1636.avif",
  objectives: [
    "Understand AI fundamentals",
    "Use AI tools for productivity",
    "Explore creative applications",
    "Implement AI in daily work",
  ],
  curriculum: [
      { name: "AI and Machine Learning Basics", subModules: ["What is AI?", "Types of ML", "Key Concepts"] },
      { name: "Generative AI Applications", subModules: ["Text Generation", "Image Generation", "Music Generation"] },
      { name: "Prompt Engineering", subModules: ["Effective Prompts", "Iterative Prompting", "Prompt Best Practices"] },
      { name: "AI Tools for Content Creation", subModules: ["ChatGPT", "Midjourney", "DALL-E"] },
      { name: "Ethics and Responsible AI", subModules: ["Bias", "Fairness", "Transparency"] },
      { name: "Future of AI in Industry", subModules: ["Impact on Jobs", "New Opportunities", "Industry Trends"] },
    ],
    prerequisites: "None",
    certification: "AI Literacy Certificate",
  quizzes: [
      {
        id: 1001,
        title: "Generative AI Introduction Quiz",
        description: "A basic quiz on Generative AI concepts.",
        questions: [
          {
            id: 1,
            text: "Which of these is an example of Generative AI?",
            type: "multiple-choice",
            options: ["Image Recognition", "Spam Detection", "Text Generation", "Data Sorting"],
            correctAnswer: "Text Generation",
          },
          {
            id: 2,
            text: "True or False: Prompt engineering is the process of designing effective inputs for AI models.",
            type: "true-false",
            options: ["True", "False"],
            correctAnswer: "True",
          },
        ],
      },
    ],
  },

{
  id: 11,
  title: "Visualization with Excel",
  desc: "Use Excel's features for impactful data visualization.",
  category: "Digital Tools",
  level: "Intermediate",
  duration: "24 hours",
  modules: 6,
  image:"OIP (1).jpg",
  objectives: [
    "Create professional charts and graphs",
    "Design interactive dashboards",
    "Use advanced charting features",
    "Present data effectively",
  ],
  curriculum: [
      { name: "Chart Types and Selection", subModules: ["Column", "Line", "Pie", "Bar"] },
      { name: "Formatting and Customization", subModules: ["Titles", "Labels", "Colors", "Styles"] },
      { name: "Dynamic Charts with Formulas", subModules: ["Named Ranges", "OFFSET", "INDEX/MATCH"] },
      { name: "Dashboard Design in Excel", subModules: ["Layout", "Interactivity", "Slicers"] },
      { name: "Interactive Elements", subModules: ["Form Controls", "Spin Buttons", "Scroll Bars"] },
      { name: "Presentation and Storytelling", subModules: ["Audience Analysis", "Key Message", "Visual Impact"] },
    ],
    prerequisites: "Excel Basic knowledge",
    certification: "Excel Visualization Specialist",
     quizzes: [
      {
        id: 1101,
        title: "Excel Visualization Quiz",
        description: "Test your skills in creating effective data visualizations in Excel.",
        questions: [
          {
            id: 1,
            text: "Which Excel feature is best for creating interactive dashboards?",
            type: "multiple-choice",
            options: ["Formulas", "Macros", "Pivot Charts", "Data Validation"],
            correctAnswer: "Pivot Charts",
          },
          {
            id: 2,
            text: "True or False: You can use conditional formatting to highlight data in charts.",
            type: "true-false",
            options: ["True", "False"],
            correctAnswer: "False", // Conditional formatting is for cells, not directly charts.
          },
        ],
      },
    ],
  
  },
]
export const facilities = [
{ name: "Power Plant", desc: "Advanced thermal power generation facility", icon: "⚡" },
{ name: "Steel Melting Shop", desc: "Electric arc furnace operations", icon: "🔥" },
{ name: "Sinter Plant", desc: "Iron ore processing and agglomeration", icon: "🏭" },
{ name: "Hot Strip Mill", desc: "Steel rolling and shaping operations", icon: "🔧" },
{ name: "Blast Furnace", desc: "Iron production from iron ore", icon: "🏗️" },
{ name: "Coke Oven", desc: "Metallurgical coke production", icon: "⚙️" },
]

export const achievements = {
yearsInOperation: 45,
totalEmployeesTrained: 56000,
yearlyTraining: 9000,
partnerships: 60,
recognitions: [
  "Best Learning Initiative 2024 - Indian Steel Industry",
  "Tata Steel shines with worldsteel’s 2024 Safety and Health Excellence Award",
  "Digital Transformation Leader - NASSCOM",
  "Tata Steel Awarded Steel Sustainability Champion Title for 2025",
],
}

export const trainingModules = {
Technical: [
  { name: "SAP Systems", modules: 12, icon: "💻" },
  { name: "Plant Operations", modules: 8, icon: "🏭" },
  { name: "Quality Control", modules: 6, icon: "🔍" },
  { name: "Maintenance Systems", modules: 10, icon: "🔧" },
],
Safety: [
  { name: "Workplace Safety", modules: 5, icon: "🦺" },
  { name: "Emergency Procedures", modules: 4, icon: "🚨" },
  { name: "Equipment Safety", modules: 6, icon: "⚠️" },
  { name: "Environmental Safety", modules: 3, icon: "🌱" },
],
"Soft Skills": [
  { name: "Communication", modules: 4, icon: "💬" },
  { name: "Team Building", modules: 3, icon: "👥" },
  { name: "Problem Solving", modules: 5, icon: "🧩" },
  { name: "Time Management", modules: 2, icon: "⏰" },
],
Leadership: [
  { name: "Strategic Thinking", modules: 6, icon: "🎯" },
  { name: "Change Management", modules: 4, icon: "🔄" },
  { name: "Performance Management", modules: 5, icon: "📊" },
  { name: "Decision Making", modules: 3, icon: "⚖️" },
],
}

export const initialUpcomingPrograms = [
{
  id: 1,
  date: "2025-06-20",
  title: "Advanced Excel Workshop",
  type: "Technical",
  department: "Finance",
  registered: false,
  attended: false,
},
{
  id: 2,
  date: "2025-06-25",
  title: "Leadership Essentials",
  type: "Leadership",
  department: "Management",
  registered: false,
  attended: false,
},
{
  id: 3,
  date: "2025-07-01",
  title: "Safety Protocol Update",
  type: "Safety",
  department: "Operations",
  registered: false,
  attended: false,
},
{
  id: 4,
  date: "2025-07-05",
  title: "Data Analytics Bootcamp",
  type: "Technical",
  department: "IT",
  registered: false,
  attended: false,
},
{
  id: 5,
  date: "2025-07-10",
  title: "Communication Skills",
  type: "Soft Skills",
  department: "HR",
  registered: false,
  attended: false,
},
{
  id: 6,
  date: "2025-07-15",
  title: "SAP PM Training",
  type: "Technical",
  department: "Maintenance",
  registered: false,
  attended: false,
},
]

export const testimonials = [
{
  name: "Arayan Sinha",
  role: "Plant Manager",
  text: "The SAP PM training transformed how we handle maintenance operations. Our efficiency improved by 30%,Self-managing, typically no formally assigned leader.",
  rating: 5,
},
{
  name: "Priyanka Sharma",
  role: "Data Analyst",
  text: "The Data Analytics course gave me the skills to make data-driven decisions that impact our bottom line.",
  rating: 5,
},
{
  name: "Biren Nayak",
  role: "Safety Officer",
  text: "safety training is more crucial than ever. It not only ensures compliance with laws and regulations but also fosters a safety culture that can significantly improve productivity and employee morale.",
  rating: 5,
},
]
